### ISSUE TITLE
demo没有实现gif上的效果

### ISSUE THREAD

**Issue by HousTracy** [vienan/TimeLine#4]
您好，怎么实现gif上的效果滑动子Item时其他Item滑动关闭

**Comment by ditclear** [comment]
现在有了
使用了保留一个静态类的方法解决复用问题，并在onDetachedFromWindow方法中进行关闭操作
具体见[SwipeDragLayout](https://github.com/vienan/TimeLine/blob/master/swipelayout/src/main/java/com/ditclear/swipelayout/SwipeDragLayout.java) 中`mCacheView`的使用方法

ps:最近几个月一直处于忙碌的状态，勿怪
