### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by liufanfandev** [vienan/TimeLine#5]
点击事件并不是真正的点击事件，和ACTION—DOWN的效果一样，是触摸事件。

**Comment by ditclear** [comment]
嗯，最近工作很忙
今天有时间重写了[SwipeDragLayout](https://github.com/vienan/TimeLine/blob/master/swipelayout/src/main/java/com/ditclear/swipelayout/SwipeDragLayout.java),以前没有点击事件是因为那时还没加，又没时间改，就耽搁了
