### ISSUE TITLE
在recyclerView 里下拉刷新有冲突

### ISSUE THREAD

**Issue by AlphaXu917** [vienan/TimeLine#8]
在recyclerView 里下拉刷新有冲突，下拉刷新跟左右滑动有冲突，没法下拉刷新

**Comment by ditclear** [comment]
我刚才试验了SwipeRefreshLayout和https://github.com/Yalantis/pull-to-make-soup ，都能够正常下拉的.
我已经更新了example和demo.apk ，你可以下载试试。
可能的原因是你的刷新布局中也有横向的事件冲突了。
> 建议可以使用这个库 https://github.com/Y-bao/PullRefreshView
